=== aureliano/da-mihi-logs/src/main/resources/configuration-schema/event-collector-configuration.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Events collector configuration schema.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Event collector id.",
      "default": "Auto-generated id."
    },
    "persistExecutionLog": {
      "type": "boolean",
      "description": "Whether it has to persist to disk log execution or not.",
      "default": "false"
    },
    "multiThreadingEnabled": {
      "type": "boolean",
      "description": "Whether it has to enable multi-threading. That means: for each input a new thread will be created.",
      "default": "false"
    },
    "metadata": {
      "type": "object",
      "description": "A key-value hash <string, string> in order to exchange metadata between configurations (main, inputs and outputs)."
    },
    "scheduler": {
      "$ref": "eventCollectionSchedule"
    },
    "reporters": {
      "type": "array",
      "items": {
        "type": { "$ref": "reporter" }
      }
    },
    "cleaners": {
      "type": "array",
      "items": {
        "type": { "$ref": "cleaner" }
      }
    },
    "eventsCollectorListeners": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": { "$ref": "input" }
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "type": { "$ref": "output" }
      }
    }
  }
}

=== aureliano/da-mihi-logs/src/test/resources/configuration.json
{
  "id": "app-log-collector",
  "persistExecutionLog": true,
  "multiThreadingEnabled": true,
  "metadata": {
    "test": "something"
  },
  "scheduler": {
    "type": "execute_periodically",
    "delay": "1",
    "period": "10",
    "timeUnit": "minutes"
  },
  "reporters": [
    {
      "type": "html",
      "language": "portuguese",
      "title": "Da mihi logs",
      "description": "Test configuration",
      "outputDir": "target/some/dir"
    }
  ],
  "cleaners": [
    {
      "type": "file",
      "directory": "target/cleaner",
      "fileNameRegex": "\\w+",
      "removeFilesAfter": {
        "timeUnit": "hours",
        "value": "1"
      }
    },
    {
      "type": "log",
      "removeLogDataFilesAfter": {
        "fileNameRegex": "[\\w\\d]+\\.log",
        "timeUnit": "hours",
        "value": "1"
      },
      "removeLogEchoFilesAfter": {
        "fileNameRegex": "[\\w\\d]+\\.log",
        "timeUnit": "hours",
        "value": "1"
      }
    }
  ],
  "eventsCollectorListeners": ["com.github.aureliano.damihilogs.listener.DefaultEventsCollectorListener"],

  "inputs": [
    {
      "id": "in-cmd",
      "type": "external_command",
      "metadata": {
        "server": "server-host"
      },

      "command": "ls",
      "parameters": ["-la"]
    },
    {
      "id": "in-file",
      "type": "file",
      "metadata": {
        "server": "banânia"
      },

      "file": "target/test/file",
      "startPosition": 1984,
      "encoding": "ISO-8859-1"
    },
    {
      "id": "in-file-tailer",
      "type": "file_tailer",
      "metadata": {
        "server": "banânia"
      },

      "file": "target/test/file",
      "encoding": "ISO-8859-1",
      "tailDelay": 5000,
      "tailInterval": 120000000
    },
    {
      "id": "in-strd",
      "type": "standard",
      "matcher": "com.github.aureliano.damihilogs.matcher.SingleLineMatcher",
      "useLastExecutionLog": true,
      "exceptionHandlers": ["com.github.aureliano.damihilogs.exception.DefaultExceptionHandler"],
      "dataReadingListeners": ["com.github.aureliano.damihilogs.listener.DefaultDataReadingListener"],
      "executionListeners": ["com.github.aureliano.damihilogs.listener.DefaultExecutionListener"],
      "metadata": {
        "server": "bananistão"
      }
    },
    {
      "id": "in-url",
      "type": "url",
      "metadata": {
        "country": "banânia",
        "leader": "babalorixá"
      },

      "connectionSchema": "https",
      "host": "localhost",
      "port": 8081,
      "path": "system",
      "readTimeOut": 5000,
      "byteOffSet": 0,
      "outputFile": "src/test/resources/compressed.gz",
      "user": "user_name",
      "password": "user_pass",

      "decompressFile": {
        "type": "gzip",
        "inputFilePath": "src/test/resources/compressed.gz",
        "outputFilePath": "target/test/output"
      }
    },
    {
      "id": "in-jdbc",
      "type": "jdbc",
      "metadata": {
        "philosopher": "Socrates"
      },
      
      "connection": {
        "user": "tomas_torquemada",
        "password": "Px",
        "driver": "org.postgresql.Driver",
        "sql": "select * from spanish where really_converted is false",
        "url": "jdbc:postgresql://127.0.0.1:5432/europe"
      }
    },
    {
      "id": "in-twitter",
      "type": "twitter",
      "metadata": {
        "philosopher": "Plato"
      },
      
      "consumerKey": "consumer-key",
      "consumerSecret": "consumer-secret",
      "oauthToken": "oauth-token",
      "oauthTokenSecret": "oauth-token-secret",
      "track": [
        "my first tweet",
        "APVD AMICVS",
        "REX CAELESTIS"
      ],
      "locations": [
        {
          "fromLocation": {
            "latitude": -19.9225,
            "longitude": -43.9450
          },
          "toLocation": {
            "latitude": -20.000,
            "longitude": -44.0
          }
        }
      ]
    }
  ],

  "outputs": [
    {
      "type": "elastic_search",
      "metadata": {
        "crusader": "Jacques de Moley"
      },

      "host": "127.0.0.1",
      "port": 9200,
      "printElasticSearchLog": "true",
      "index": "my-index",
      "mappingType": "new-type"
    },
    {
      "type": "file",
      "metadata": {
        "crusader": "Hugo de Payens"
      },
      
      "file": "src/test/resources/server.log",
      "append": "true",
      "encoding": "ISO-8859-1"
    },
    {
      "type": "standard",
      "parser": "com.github.aureliano.damihilogs.parser.PlainTextParser",
      "filter": "com.github.aureliano.damihilogs.filter.DefaultEmptyFilter",
      "formatter": "com.github.aureliano.damihilogs.formatter.PlainTextFormatter",
      "dataWritingListeners": ["com.github.aureliano.damihilogs.listener.DefaultDataWritingListener"],
      "metadata": {
        "inquisitor": "Bernardus Guidonis"
      }
    },
    {
      "type": "jdbc",
      "parser": "com.github.aureliano.damihilogs.parser.PlainTextParser",
      "filter": "com.github.aureliano.damihilogs.filter.DefaultEmptyFilter",
      "formatter": "com.github.aureliano.damihilogs.formatter.PlainTextFormatter",
      "dataWritingListeners": ["com.github.aureliano.damihilogs.listener.DefaultDataWritingListener"],
      "metadata": {
        "philosopher": "Socrates"
      },
      
      "connection": {
        "user": "tomas_torquemada",
        "password": "Px",
        "driver": "org.postgresql.Driver",
        "sql": "select * from spanish where really_converted is false",
        "url": "jdbc:postgresql://127.0.0.1:5432/europe"
      }
    },
    {
      "type": "twitter",
      "parser": "com.github.aureliano.damihilogs.parser.PlainTextParser",
      "filter": "com.github.aureliano.damihilogs.filter.DefaultEmptyFilter",
      "formatter": "com.github.aureliano.damihilogs.formatter.PlainTextFormatter",
      "dataWritingListeners": ["com.github.aureliano.damihilogs.listener.DefaultDataWritingListener"],
      "metadata": {
        "crusader": "Godefroy de Bouillon"
      },
      
      "consumerKey": "consumer-key",
      "consumerSecret": "consumer-secret",
      "oauthToken": "oauth-token",
      "oauthTokenSecret": "oauth-token-secret",
      "tweet": "¡Viva Cristo Rey! ¡Viva la Virgen de Guadalupe!"
    }
  ]
}
